# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RPSGui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 515)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 171, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelDisOpponentsHand = QtWidgets.QLabel(self.frame)
        self.labelDisOpponentsHand.setGeometry(QtCore.QRect(10, 10, 151, 161))
        self.labelDisOpponentsHand.setText("")
        self.labelDisOpponentsHand.setObjectName("labelDisOpponentsHand")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 260, 171, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.labelDisPlayerHand = QtWidgets.QLabel(self.frame_2)
        self.labelDisPlayerHand.setGeometry(QtCore.QRect(10, 20, 151, 141))
        self.labelDisPlayerHand.setText("")
        self.labelDisPlayerHand.setObjectName("labelDisPlayerHand")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(210, 40, 181, 181))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.labelTitleGamesPlayed = QtWidgets.QLabel(self.frame_3)
        self.labelTitleGamesPlayed.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelTitleGamesPlayed.setFont(font)
        self.labelTitleGamesPlayed.setObjectName("labelTitleGamesPlayed")
        self.textBrowserDisGamesPlayed = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowserDisGamesPlayed.setEnabled(False)
        self.textBrowserDisGamesPlayed.setGeometry(QtCore.QRect(100, 30, 61, 31))
        self.textBrowserDisGamesPlayed.setObjectName("textBrowserDisGamesPlayed")
        self.labelTitleGamesWon = QtWidgets.QLabel(self.frame_3)
        self.labelTitleGamesWon.setGeometry(QtCore.QRect(10, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelTitleGamesWon.setFont(font)
        self.labelTitleGamesWon.setObjectName("labelTitleGamesWon")
        self.labelPercentWon = QtWidgets.QLabel(self.frame_3)
        self.labelPercentWon.setGeometry(QtCore.QRect(10, 120, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelPercentWon.setFont(font)
        self.labelPercentWon.setObjectName("labelPercentWon")
        self.textBrowserDisPercentWon = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowserDisPercentWon.setEnabled(False)
        self.textBrowserDisPercentWon.setGeometry(QtCore.QRect(100, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowserDisPercentWon.setFont(font)
        self.textBrowserDisPercentWon.setObjectName("textBrowserDisPercentWon")
        self.textBrowserDisGamesWon = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowserDisGamesWon.setEnabled(False)
        self.textBrowserDisGamesWon.setGeometry(QtCore.QRect(100, 70, 61, 31))
        self.textBrowserDisGamesWon.setObjectName("textBrowserDisGamesWon")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(210, 260, 191, 101))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButtonRock = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonRock.setGeometry(QtCore.QRect(10, 20, 51, 61))
        self.pushButtonRock.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Rock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRock.setIcon(icon)
        self.pushButtonRock.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonRock.setObjectName("pushButtonRock")
        self.pushButtonPapper = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonPapper.setGeometry(QtCore.QRect(70, 20, 51, 61))
        self.pushButtonPapper.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Papper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPapper.setIcon(icon1)
        self.pushButtonPapper.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonPapper.setObjectName("pushButtonPapper")
        self.pushButtonScissors = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonScissors.setGeometry(QtCore.QRect(130, 20, 51, 61))
        self.pushButtonScissors.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Scissors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonScissors.setIcon(icon2)
        self.pushButtonScissors.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonScissors.setObjectName("pushButtonScissors")
        self.labelTitleOpponent = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleOpponent.setGeometry(QtCore.QRect(20, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTitleOpponent.setFont(font)
        self.labelTitleOpponent.setObjectName("labelTitleOpponent")
        self.labelPlayer = QtWidgets.QLabel(self.centralwidget)
        self.labelPlayer.setGeometry(QtCore.QRect(20, 232, 111, 31))
        self.labelPlayer.setObjectName("labelPlayer")
        self.labelPlayerThrow = QtWidgets.QLabel(self.centralwidget)
        self.labelPlayerThrow.setGeometry(QtCore.QRect(210, 240, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPlayerThrow.setFont(font)
        self.labelPlayerThrow.setObjectName("labelPlayerThrow")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 413, 21))
        self.menubar.setObjectName("menubar")
        self.menuNew_Game = QtWidgets.QMenu(self.menubar)
        self.menuNew_Game.setObjectName("menuNew_Game")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionNew_Game.setFont(font)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuNew_Game.addAction(self.actionNew_Game)
        self.menuNew_Game.addSeparator()
        self.menuNew_Game.addAction(self.actionExit)
        self.menubar.addAction(self.menuNew_Game.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Roack Paper Scissors!"))
        self.labelTitleGamesPlayed.setText(_translate("MainWindow", "Games Played:"))
        self.labelTitleGamesWon.setText(_translate("MainWindow", "Games won:"))
        self.labelPercentWon.setText(_translate("MainWindow", "Percent Won:"))
        self.labelTitleOpponent.setText(_translate("MainWindow", "Opponents Hand"))
        self.labelPlayer.setText(_translate("MainWindow", "Players Hand"))
        self.labelPlayerThrow.setText(_translate("MainWindow", "Players throw"))
        self.label.setText(_translate("MainWindow", "Game Stats"))
        self.menuNew_Game.setTitle(_translate("MainWindow", "Tools"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game"))
        self.actionExit.setText(_translate("MainWindow", "Exit..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

